{"time":"2024-12-16T13:27:18.2256445+01:00","level":"INFO","msg":"using version","core version":"0.19.0"}
{"time":"2024-12-16T13:27:18.2256445+01:00","level":"INFO","msg":"created symlink","path":"c:\\Users\\jarro\\Documents\\GitHub\\2023-24d-fai1-adsai-teamwork-t19\\2024-25b-fai2-adsai-JarroTeunissen231667\\datalab_tasks\\task9\\Reinforcement learning\\wandb\\run-20241216_132718-zp5umggu\\logs\\debug-core.log"}
{"time":"2024-12-16T13:27:18.3392946+01:00","level":"INFO","msg":"created new stream","id":"zp5umggu"}
{"time":"2024-12-16T13:27:18.3392946+01:00","level":"INFO","msg":"stream: started","id":"zp5umggu"}
{"time":"2024-12-16T13:27:18.3392946+01:00","level":"INFO","msg":"handler: started","stream_id":"zp5umggu"}
{"time":"2024-12-16T13:27:18.3392946+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"zp5umggu"}
{"time":"2024-12-16T13:27:18.3392946+01:00","level":"INFO","msg":"sender: started","stream_id":"zp5umggu"}
{"time":"2024-12-16T13:27:18.8613482+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-12-16T13:27:22.2101803+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2024-12-16T13:27:29.6637516+01:00","level":"INFO","msg":"tensorboard: no root directory after 10 seconds, using working directory"}
{"time":"2024-12-16T13:27:29.6671378+01:00","level":"ERROR","msg":"tensorboard: error creating symlink","target":"c:\\Users\\jarro\\Documents\\GitHub\\2023-24d-fai1-adsai-teamwork-t19\\2024-25b-fai2-adsai-JarroTeunissen231667\\datalab_tasks\\task9\\Reinforcement learning\\runs\\zp5umggu\\runs\\zp5umggu_1\\events.out.tfevents.1734352039.JarroLaptop.36164.0","symlink":"c:\\Users\\jarro\\Documents\\GitHub\\2023-24d-fai1-adsai-teamwork-t19\\2024-25b-fai2-adsai-JarroTeunissen231667\\datalab_tasks\\task9\\Reinforcement learning\\wandb\\run-20241216_132718-zp5umggu\\files\\runs\\zp5umggu\\runs\\zp5umggu_1\\events.out.tfevents.1734352039.JarroLaptop.36164.0","error":"symlink c:\\Users\\jarro\\Documents\\GitHub\\2023-24d-fai1-adsai-teamwork-t19\\2024-25b-fai2-adsai-JarroTeunissen231667\\datalab_tasks\\task9\\Reinforcement learning\\runs\\zp5umggu\\runs\\zp5umggu_1\\events.out.tfevents.1734352039.JarroLaptop.36164.0 c:\\Users\\jarro\\Documents\\GitHub\\2023-24d-fai1-adsai-teamwork-t19\\2024-25b-fai2-adsai-JarroTeunissen231667\\datalab_tasks\\task9\\Reinforcement learning\\wandb\\run-20241216_132718-zp5umggu\\files\\runs\\zp5umggu\\runs\\zp5umggu_1\\events.out.tfevents.1734352039.JarroLaptop.36164.0: A required privilege is not held by the client."}
{"time":"2024-12-16T13:29:04.7062287+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/231667-breda-university-of-applied-sciences/sb3_pendulum_demo/zp5umggu/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:29:08.564193+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp [2a02:a420:238:a25f:6465:d446:4bd1:ba29]:54118->[64:ff9b::23ba:e431]:443: wsarecv: An established connection was aborted by the software in your host machine."}
{"time":"2024-12-16T13:29:56.1088049+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 145.101.231.114:54429->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-16T13:29:58.4808252+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:30:03.0001303+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:30:12.8567983+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:30:31.9221953+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:31:07.9100657+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-16T13:31:26.9087875+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/231667-breda-university-of-applied-sciences/sb3_pendulum_demo/zp5umggu/file_stream\": read tcp 145.101.231.114:54535->35.186.228.49:443: wsarecv: An established connection was aborted by the software in your host machine."}
